name: Estoque Grade Daily Update

on:
  workflow_dispatch:  # Permite execução manual
  schedule:
    # 21h30 BRT (GMT-3) = 00:30 UTC
    - cron: '30 0 * * *'

concurrency:
  group: estoque-grade
  cancel-in-progress: true

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Biblioteca para Google Sheets API
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Create .env for database connection
        run: |
          cat > .env <<'ENV'
          FB_HOST=${{ secrets.SYNDATA_HOST }}
          FB_PORT=${{ secrets.SYNDATA_PORT }}
          FB_PATH=${{ secrets.SYNDATA_DB_PATH }}
          FB_USER=${{ secrets.SYNDATA_USER }}
          FB_PASS=${{ secrets.SYNDATA_PASSWORD }}
          FB_CHARSET=${{ secrets.SYNDATA_CHARSET }}
          ENV

      - name: Show .env (masked)
        run: |
          echo "==== .env (mascarado pelo GitHub) ===="
          cat .env

      - name: Run estoque_grade.py
        run: |
          mkdir -p output
          python estoque_grade.py
          echo "=== Arquivo gerado ==="
          ls -lh output/ESTOQUE_GRADE.csv

      - name: Write Google Service Account credentials
        run: |
          echo '${{ secrets.GDRIVE_SA_JSON }}' > google_sa.json

      - name: Upload to Google Sheets
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/google_sa.json
          SHEET_ID: ${{ secrets.DRIVE_FILE_ID_ESTOQUE_GRADE }}
          CSV_FILE: output/ESTOQUE_GRADE.csv
          SHEET_NAME: ESTOQUE_GRADE
        run: |
          python upload_to_sheets.py

      - name: Cleanup
        run: |
          echo "🧹 Limpando arquivos temporários..."
          rm -f google_sa.json
          echo "✅ Concluído!"